# ����˿�
server.port=8205
# ������
spring.application.name=service-oss

#�ϴ��ļ����������
spring.servlet.multipart.maxFileSize=5MB
spring.servlet.multipart.maxRequestSize=5MB

#����json��ȫ��ʱ���ʽ
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=GMT+8

# nacos�����ַ
spring.cloud.nacos.discovery.server-addr=${NACOS_SERVER_ADDR:127.0.0.1:8848}

aliyun.oss.endpoint=${ALIYUN_OSS_ENDPOINT:oss-cn-shanghai.aliyuncs.com}
aliyun.oss.accessKeyId=${ALIYUN_OSS_ACCESS_KEY_ID}
aliyun.oss.secret=${ALIYUN_OSS_SECRET}
aliyun.oss.bucket=${ALIYUN_OSS_BUCKET}
