# ����˿�
server.port=8208
# ������
spring.application.name=service-statistics
# �������ã�dev��test��prod
spring.profiles.active=dev

# nacos�����ַ
spring.cloud.nacos.discovery.server-addr=${NACOS_SERVER_ADDR:127.0.0.1:8848}