# ����˿�
server.port=8204
# ������
spring.application.name=service-msm

#����json��ȫ��ʱ���ʽ
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=GMT+8

spring.redis.host=${REDIS_HOST:127.0.0.1}
spring.redis.port=${REDIS_PORT:6379}
spring.redis.database= 2
spring.redis.password=${REDIS_PASSWORD:}
spring.redis.timeout=1800000
spring.redis.lettuce.pool.max-active=20
spring.redis.lettuce.pool.max-wait=-1
#��������ȴ�ʱ��(������ʾû����)
spring.redis.lettuce.pool.max-idle=5
spring.redis.lettuce.pool.min-idle=0

# nacos�����ַ
spring.cloud.nacos.discovery.server-addr=${NACOS_SERVER_ADDR:127.0.0.1:8848}

#���Ͷ��ŷ�ʽһ ������
aliyun.sms.regionId=${ALIYUN_SMS_REGION_ID:default}
aliyun.sms.accessKeyId=${ALIYUN_SMS_ACCESS_KEY_ID}
aliyun.sms.secret=${ALIYUN_SMS_SECRET}

#���Ͷ��ŷ�ʽ��  ��Ѷ��
sms.qcloud.appId=${SMS_QCLOUD_APP_ID:}
sms.qcloud.appKey=${SMS_QCLOUD_APP_KEY:}
sms.qcloud.templateId=${SMS_QCLOUD_TEMPLATE_ID:}
sms.qcloud.sign=${SMS_QCLOUD_SIGN:}

#rabbitmq��ַ
spring.rabbitmq.host=${RABBITMQ_HOST:127.0.0.1}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}
